name: Bug report
description: Report a problem
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior

  - type: textarea
    id: env
    attributes:
      label: Environment
