name: Workflow CI

on: 
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        net-version: ['8.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.net-version}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.net-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
  test:
    needs : build
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest]
        net-version: ['8.x']
      fail-fast: false
    steps:
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.net-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
          if: ${{ always() }}
