name: Workflow CI

on: 
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        net-version: ['8.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.net-version}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.net-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        net-version: ['8.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix['net-version'] }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix['net-version'] }}
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.net-version }}"
